### ISSUE TITLE
Can't import oxford dictionary

### ISSUE THREAD

**Issue by perlop** [MichaelPetre/MigakuDicts#3]
Hello.
I can't import the oxford dictionary in this repo. I'm on the latest migaku browser extension from chrome store.

Here is error:
<img width="332" alt="image" src="https://user-images.githubusercontent.com/14243372/156144799-c2fb6f5c-d3c4-4ef5-a3f3-6072ff1838a1.png">

**Comment by MichaelPetre** [comment]
I'll check later today!

**Comment by MichaelPetre** [comment]
Please download the new file, it imports fine now. It turns out there were some errors in the source file and I totally missed them.

**Comment by perlop** [comment]
Thanks.
